<a href="https://colab.research.google.com/github/arn97/MLTSA25_ARoy/blob/main/project/Preprocessing/MLTSA_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
import numpy as np
import json
import os

In [9]:
from google.colab import drive

drive.mount("/content/gdrive")

Mounted at /content/gdrive

In [10]:
cd /content

/content

In [11]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [12]:
ls kaggle.json

kaggle.json

In [13]:
envs = json.load(open("kaggle.json", "r"))
os.environ["KAGGLE_USERNAME"] = envs['username']
os.environ["KAGGLE_KEY"] = envs['key']

In [14]:
cd /content/gdrive/MyDrive/MLTSA25

[Errno 107] Transport endpoint is not connected: '/content/gdrive/MyDrive/MLTSA25'
/content

In [15]:
!mkdir Project

In [16]:
cd Project

/content/Project

In [17]:
!kaggle competitions download -c m5-forecasting-accuracy

Downloading m5-forecasting-accuracy.zip to /content/Project
 98% 45.0M/45.8M [00:00<00:00, 131MB/s]
100% 45.8M/45.8M [00:00<00:00, 119MB/s]

In [18]:
!unzip m5-forecasting-accuracy.zip

Archive:  m5-forecasting-accuracy.zip
  inflating: calendar.csv
  inflating: sales_train_evaluation.csv
  inflating: sales_train_validation.csv
  inflating: sample_submission.csv
  inflating: sell_prices.csv

In [19]:
df_calendar = pd.read_csv("calendar.csv")

In [20]:
df_calendar.columns

Index(['date', 'wm_yr_wk', 'weekday', 'wday', 'month', 'year', 'd',
       'event_name_1', 'event_type_1', 'event_name_2', 'event_type_2',
       'snap_CA', 'snap_TX', 'snap_WI'],
      dtype='object')

In [21]:
df_calendar.head()

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,NaN,NaN,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,NaN,NaN,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,NaN,NaN,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,NaN,NaN,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,NaN,NaN,1,0,1

In [22]:
df_calendar.tail()

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
1964,2016-06-15,11620,Wednesday,5,6,2016,d_1965,NaN,NaN,NaN,NaN,0,1,1
1965,2016-06-16,11620,Thursday,6,6,2016,d_1966,NaN,NaN,NaN,NaN,0,0,0
1966,2016-06-17,11620,Friday,7,6,2016,d_1967,NaN,NaN,NaN,NaN,0,0,0
1967,2016-06-18,11621,Saturday,1,6,2016,d_1968,NaN,NaN,NaN,NaN,0,0,0
1968,2016-06-19,11621,Sunday,2,6,2016,d_1969,NBAFinalsEnd,Sporting,Father's day,Cultural,0,0,0

In [23]:
df_sales_training = pd.read_csv("sales_train_validation.csv")

In [24]:
df_sales_training.columns

Index(['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'd_1',
       'd_2', 'd_3', 'd_4',
       ...
       'd_1904', 'd_1905', 'd_1906', 'd_1907', 'd_1908', 'd_1909', 'd_1910',
       'd_1911', 'd_1912', 'd_1913'],
      dtype='object', length=1919)

In [25]:
df_sales_training.shape

(30490, 1919)

In [49]:
df_sales_training

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,3,0,1,1,1,3,0,1,1
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,2,1,1,1,0,1,1,1
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,5,4,1,0,1,3,7,2
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,1,0,1,1,2,2,2,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30485,FOODS_3_823_WI_3_validation,FOODS_3_823,FOODS_3,FOODS,WI_3,WI,0,0,2,2,...,2,0,0,0,0,0,1,0,0,1
30486,FOODS_3_824_WI_3_validation,FOODS_3_824,FOODS_3,FOODS,WI_3,WI,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
30487,FOODS_3_825_WI_3_validation,FOODS_3_825,FOODS_3,FOODS,WI_3,WI,0,6,0,2,...,2,1,0,2,0,1,0,0,1,0
30488,FOODS_3_826_WI_3_validation,FOODS_3_826,FOODS_3,FOODS,WI_3,WI,0,0,0,0,...,0,0,1,0,0,1,0,3,1,3
30489,FOODS_3_827_WI_3_validation,FOODS_3_827,FOODS_3,FOODS,WI_3,WI,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [27]:
df_sales=pd.read_csv("sales_train_evaluation.csv")

In [50]:
df_sales

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1932,d_1933,d_1934,d_1935,d_1936,d_1937,d_1938,d_1939,d_1940,d_1941
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,4,0,0,0,0,3,3,0,1
1,HOBBIES_1_002_CA_1_evaluation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,1,2,1,1,0,0,0,0,0
2,HOBBIES_1_003_CA_1_evaluation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,2,0,0,0,2,3,0,1
3,HOBBIES_1_004_CA_1_evaluation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,1,0,4,0,1,3,0,2,6
4,HOBBIES_1_005_CA_1_evaluation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,2,1,0,0,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30485,FOODS_3_823_WI_3_evaluation,FOODS_3_823,FOODS_3,FOODS,WI_3,WI,0,0,2,2,...,1,0,3,0,1,1,0,0,1,1
30486,FOODS_3_824_WI_3_evaluation,FOODS_3_824,FOODS_3,FOODS,WI_3,WI,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
30487,FOODS_3_825_WI_3_evaluation,FOODS_3_825,FOODS_3,FOODS,WI_3,WI,0,6,0,2,...,0,0,1,2,0,1,0,1,0,2
30488,FOODS_3_826_WI_3_evaluation,FOODS_3_826,FOODS_3,FOODS,WI_3,WI,0,0,0,0,...,1,1,1,4,6,0,1,1,1,0
30489,FOODS_3_827_WI_3_evaluation,FOODS_3_827,FOODS_3,FOODS,WI_3,WI,0,0,0,0,...,1,2,0,5,4,0,2,2,5,1

In [29]:
df_sample_submission = pd.read_csv("sample_submission.csv")

In [30]:
df_sample_submission.head()

,id,F1,F2,F3,F4,F5,F6,F7,F8,F9,...,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28
0,HOBBIES_1_001_CA_1_validation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,HOBBIES_1_002_CA_1_validation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,HOBBIES_1_003_CA_1_validation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,HOBBIES_1_004_CA_1_validation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,HOBBIES_1_005_CA_1_validation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [31]:
df_sell_prices = pd.read_csv("sell_prices.csv")

In [32]:
df_sell_prices.head()

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26

In [33]:
def downcast(df):
    cols = df.dtypes.index.tolist()
    types = df.dtypes.values.tolist()
    for i,t in enumerate(types):
        if 'int' in str(t):
            if df[cols[i]].min() > np.iinfo(np.int8).min and df[cols[i]].max() < np.iinfo(np.int8).max:
                df[cols[i]] = df[cols[i]].astype(np.int8)
            elif df[cols[i]].min() > np.iinfo(np.int16).min and df[cols[i]].max() < np.iinfo(np.int16).max:
                df[cols[i]] = df[cols[i]].astype(np.int16)
            elif df[cols[i]].min() > np.iinfo(np.int32).min and df[cols[i]].max() < np.iinfo(np.int32).max:
                df[cols[i]] = df[cols[i]].astype(np.int32)
            else:
                df[cols[i]] = df[cols[i]].astype(np.int64)
        elif 'float' in str(t):
            if df[cols[i]].min() > np.finfo(np.float16).min and df[cols[i]].max() < np.finfo(np.float16).max:
                df[cols[i]] = df[cols[i]].astype(np.float16)
            elif df[cols[i]].min() > np.finfo(np.float32).min and df[cols[i]].max() < np.finfo(np.float32).max:
                df[cols[i]] = df[cols[i]].astype(np.float32)
            else:
                df[cols[i]] = df[cols[i]].astype(np.float64)
        elif t == object:
            if cols[i] == 'date':
                df[cols[i]] = pd.to_datetime(df[cols[i]], format='%Y-%m-%d')
            else:
                df[cols[i]] = df[cols[i]].astype('category')
    return df

In [34]:
salesVal = downcast(df_sales_training)
prices = downcast(df_sell_prices)
cal = downcast(df_calendar)

In [35]:
print("Before Downcasting:")
print(df_sales_training.dtypes)
print(f"Memory usage: {df_sales_training.memory_usage(deep=True).sum() / 1024:.2f} KB")


print("\nAfter Downcasting:")
print(salesVal.dtypes)
print(f"Memory usage: {salesVal.memory_usage(deep=True).sum() / 1024:.2f} KB")

Before Downcasting:
id          category
item_id     category
dept_id     category
cat_id      category
store_id    category
              ...
d_1909          int8
d_1910          int8
d_1911         int16
d_1912         int16
d_1913         int16
Length: 1919, dtype: object
Memory usage: 99944.83 KB

After Downcasting:
id          category
item_id     category
dept_id     category
cat_id      category
store_id    category
              ...
d_1909          int8
d_1910          int8
d_1911         int16
d_1912         int16
d_1913         int16
Length: 1919, dtype: object
Memory usage: 99944.83 KB

In [36]:
print("Before Downcasting:")
print(df_sell_prices.dtypes)
print(f"Memory usage: {df_sell_prices.memory_usage(deep=True).sum() / 1024:.2f} KB")


print("\nAfter Downcasting:")
print(prices.dtypes)
print(f"Memory usage: {prices.memory_usage(deep=True).sum() / 1024:.2f} KB")

Before Downcasting:
store_id      category
item_id       category
wm_yr_wk         int16
sell_price     float16
dtype: object
Memory usage: 47038.70 KB

After Downcasting:
store_id      category
item_id       category
wm_yr_wk         int16
sell_price     float16
dtype: object
Memory usage: 47038.70 KB

In [37]:
print("Before Downcasting:")
print(df_calendar.dtypes)
print(f"Memory usage: {df_calendar.memory_usage(deep=True).sum() / 1024:.2f} KB")


print("\nAfter Downcasting:")
print(cal.dtypes)
print(f"Memory usage: {cal.memory_usage(deep=True).sum() / 1024:.2f} KB")

Before Downcasting:
date            datetime64[ns]
wm_yr_wk                 int16
weekday               category
wday                      int8
month                     int8
year                     int16
d                     category
event_name_1          category
event_type_1          category
event_name_2          category
event_type_2          category
snap_CA                   int8
snap_TX                   int8
snap_WI                   int8
dtype: object
Memory usage: 235.75 KB

After Downcasting:
date            datetime64[ns]
wm_yr_wk                 int16
weekday               category
wday                      int8
month                     int8
year                     int16
d                     category
event_name_1          category
event_type_1          category
event_name_2          category
event_type_2          category
snap_CA                   int8
snap_TX                   int8
snap_WI                   int8
dtype: object
Memory usage: 235.75 KB

In [38]:
df_calendar.describe()

,date,wm_yr_wk,wday,month,year,snap_CA,snap_TX,snap_WI
count,1969,1969.000000,1969.000000,1969.000000,1969.000000,1969.000000,1969.000000,1969.000000
mean,2013-10-09 00:00:00,11347.086338,3.997461,6.325546,2013.288471,0.330117,0.330117,0.330117
min,2011-01-29 00:00:00,11101.000000,1.000000,1.000000,2011.000000,0.000000,0.000000,0.000000
25%,2012-06-04 00:00:00,11219.000000,2.000000,3.000000,2012.000000,0.000000,0.000000,0.000000
50%,2013-10-09 00:00:00,11337.000000,4.000000,6.000000,2013.000000,0.000000,0.000000,0.000000
75%,2015-02-13 00:00:00,11502.000000,6.000000,9.000000,2015.000000,1.000000,1.000000,1.000000
max,2016-06-19 00:00:00,11621.000000,7.000000,12.000000,2016.000000,1.000000,1.000000,1.000000
std,NaN,155.277043,2.001141,3.416864,1.580198,0.470374,0.470374,0.470374

In [39]:
df_sales_training.describe()

,d_1,d_2,d_3,d_4,d_5,d_6,d_7,d_8,d_9,d_10,...,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
count,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,...,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000
mean,1.070220,1.041292,0.780026,0.833454,0.627944,0.958052,0.918662,1.244080,1.073663,0.838701,...,1.370581,1.586159,1.693670,1.248245,1.232207,1.159167,1.149000,1.328862,1.605838,1.633158
std,5.126689,5.365468,3.667454,4.415141,3.379344,4.785947,5.059495,6.617729,5.917204,4.206199,...,3.740017,4.097191,4.359809,3.276925,3.125471,2.876026,2.950364,3.358012,4.089422,3.812248
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,2.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,2.000000
max,360.000000,436.000000,207.000000,323.000000,296.000000,314.000000,316.000000,370.000000,385.000000,353.000000,...,129.000000,160.000000,204.000000,98.000000,100.000000,88.000000,77.000000,141.000000,171.000000,130.000000

In [40]:
df_sell_prices.describe()

/usr/local/lib/python3.11/dist-packages/pandas/core/nanops.py:1487: RuntimeWarning: overflow encountered in cast
  return dtype.type(n)
/usr/local/lib/python3.11/dist-packages/numpy/_core/_methods.py:52: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
/usr/local/lib/python3.11/dist-packages/pandas/core/nanops.py:731: RuntimeWarning: invalid value encountered in scalar divide
  the_mean = the_sum / count if count > 0 else np.nan
/usr/local/lib/python3.11/dist-packages/pandas/core/nanops.py:1487: RuntimeWarning: overflow encountered in cast
  return dtype.type(n)

           wm_yr_wk    sell_price
count  6.841121e+06  6.841121e+06
mean   1.138294e+04           NaN
std    1.486100e+02  0.000000e+00
min    1.110100e+04  1.000214e-02
25%    1.124700e+04  2.179688e+00
50%    1.141100e+04  3.470703e+00
75%    1.151700e+04  5.839844e+00
max    1.162100e+04  1.073125e+02

In [42]:
df_sales.describe()

,d_1,d_2,d_3,d_4,d_5,d_6,d_7,d_8,d_9,d_10,...,d_1932,d_1933,d_1934,d_1935,d_1936,d_1937,d_1938,d_1939,d_1940,d_1941
count,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,...,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000
mean,1.070220,1.041292,0.780026,0.833454,0.627944,0.958052,0.918662,1.244080,1.073663,0.838701,...,1.445490,1.781174,1.965267,1.389374,1.271794,1.216661,1.212299,1.395605,1.689669,1.782158
std,5.126689,5.365468,3.667454,4.415141,3.379344,4.785947,5.059495,6.617729,5.917204,4.206199,...,3.656824,4.426550,4.706284,3.313292,3.126178,3.000348,2.955910,3.514318,4.089208,4.284356
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.000000,2.000000,2.000000,2.000000,1.000000,1.000000,1.000000,1.000000,2.000000,2.000000
max,360.000000,436.000000,207.000000,323.000000,296.000000,314.000000,316.000000,370.000000,385.000000,353.000000,...,143.000000,156.000000,187.000000,98.000000,90.000000,77.000000,84.000000,110.000000,156.000000,117.000000

In [43]:
# prompt: Count the number of columns and rows containing NAN entries in df_calendar.

# Count NaN values in columns
nan_cols = df_calendar.isna().sum()
nan_cols_count = len(nan_cols[nan_cols > 0])

# Count NaN values in rows
nan_rows = df_calendar.isna().sum(axis=1)
nan_rows_count = len(nan_rows[nan_rows > 0])

print(f"Number of columns with NaN entries: {nan_cols_count}")
print(f"Number of rows with NaN entries: {nan_rows_count}")

Number of columns with NaN entries: 4
Number of rows with NaN entries: 1964

In [44]:
# prompt: There are four columns containing NAN entries in df_calendar. Check how many rows in those columns have NAN?

# Identify columns with NaN values
nan_columns = ['event_name_1', 'event_type_1', 'event_name_2', 'event_type_2']

# Count NaN values in each specified column
nan_counts = df_calendar[nan_columns].isna().sum()

nan_counts

event_name_1    1807
event_type_1    1807
event_name_2    1964
event_type_2    1964
dtype: int64

In [46]:
# Count NaN values in columns
nan_cols = df_sales_training.isna().sum()
nan_cols_count = len(nan_cols[nan_cols > 0])

# Count NaN values in rows
nan_rows = df_sales_training.isna().sum(axis=1)
nan_rows_count = len(nan_rows[nan_rows > 0])

print(f"Number of columns with NaN entries: {nan_cols_count}")
print(f"Number of rows with NaN entries: {nan_rows_count}")

Number of columns with NaN entries: 0
Number of rows with NaN entries: 0

In [47]:
# prompt: Count the number of columns and rows containing NAN entries in df_calendar.

# Count NaN values in columns
nan_cols = df_sales.isna().sum()
nan_cols_count = len(nan_cols[nan_cols > 0])

# Count NaN values in rows
nan_rows = df_sales.isna().sum(axis=1)
nan_rows_count = len(nan_rows[nan_rows > 0])

print(f"Number of columns with NaN entries: {nan_cols_count}")
print(f"Number of rows with NaN entries: {nan_rows_count}")

Number of columns with NaN entries: 0
Number of rows with NaN entries: 0

In [48]:
# prompt: Count the number of columns and rows containing NAN entries in df_calendar.

# Count NaN values in columns
nan_cols = df_sell_prices.isna().sum()
nan_cols_count = len(nan_cols[nan_cols > 0])

# Count NaN values in rows
nan_rows = df_sell_prices.isna().sum(axis=1)
nan_rows_count = len(nan_rows[nan_rows > 0])

print(f"Number of columns with NaN entries: {nan_cols_count}")
print(f"Number of rows with NaN entries: {nan_rows_count}")

Number of columns with NaN entries: 0
Number of rows with NaN entries: 0

In [51]:
# prompt: List all the columns in calendar.csv that contains NAN values.

# Identify columns with NaN values in df_calendar
nan_columns = df_calendar.columns[df_calendar.isna().any()].tolist()

nan_columns

['event_name_1', 'event_type_1', 'event_name_2', 'event_type_2']